### ISSUE TITLE
pongo not injecting lua lists when using serve2()

### ISSUE THREAD

**Issue by seansbox** [xyproto/algernon#26]
Using Algernon 1.12.2. If I create an empty folder with these two files:

**index.po2:**

```
TEXT TEST: {{ testtext }}
{% for k, v in testlist %}
LIST TEST: {{ v }}
{% endfor %}
```

**data.lua:**

```lua
testtext = "TEST"
testlist = { "ITEM_1", "ITEM_2" }
```

When I browse to the folder it works great:

```
TEXT TEST: TEST
LIST TEST: ITEM_1
LIST TEST: ITEM_2
```

HOWEVER, when I add the following file:

**index.lua:**

```lua
serve2("index.po2", { testtext="TEST", testlist={ "ITEM_1", "ITEM_2"} })
```

If I restart the server, and refresh the folder in the browser, I instead get this:

```
TEXT TEST: TEST
```

If doesn't show the list, only the text. It doesn't seem to detect that testlist has contents.

Thoughts? I can't seem to find a workaround.

Thanks!

**Comment by xyproto** [comment]
Thanks for reporting! I will look into this.

**Comment by xyproto** [comment]
Fixed, please test.

**Comment by seansbox** [comment]
That definitely changed things, but still not the outcome I would expect. It appears the list is being converted to a string now. testlist = { "ITEM_1", "ITEM_2" } should result in 2x iterations of the pongo2 loop (and it still does using the index.po2/data.lua method), but it's only iterating 1 time with the whole list as a string when using serve2().

Now I get this:

    TEXT TEST: TEST
    LIST TEST: ITEM_1, ITEM_2

But I should get this:

    TEXT TEST: TEST
    LIST TEST: ITEM_1
    LIST TEST: ITEM_2

**Comment by xyproto** [comment]
Thanks for testing!

I created a test for this in `regtest/issue26`, but I'm unable to reproduce this latest issue. When using `serve2()`, it seems to iterate correctly over the items, as far as I can tell.

Could you please take a quick look at the `regtest/issue26` example and modify it so that it demonstrates the issue, or provide a quick example, so that I can reproduce the issue?

**Comment by seansbox** [comment]
Can do!

**Comment by seansbox** [comment]
Confirmed, I cannot reproduce the issue in regtest/issue26 with the fixed version. Apparently I had a bug in my test code. This issue is closed! Thank you!

**Comment by xyproto** [comment]
Great, thanks for testing!
